---
title: "Münchner Mietspiegel 2023"
institute: 
  - "Dr. Fabian Scheipl, Dr. Sabine Hoffmann, Dr. Michael Windmann, Lisa Kleinlein"
author: 
  - "Bob Faber, Adrian Schneider, Louis Trierweiler, Karan Bal"

format:
  revealjs:
    css: presentation/customstyle.css
    embed-resources: true
    slide-number: c
    theme: simple
editor: visual
---

## Gliederung

-   Einführung
-   Überblick
-   Betrachtete Merkmale
-   Forschungsfragen
-   Limitationen & Fazit

## Einführung

-   Zentrale Frage: Wo sind die Preistreiber in München?
-   Legaler Stand (Mietpreisbremse)
    -   Wiedervermietung: max. 10% über der ortsüblichen Vergleichsmiete
    -   Bestenende Mietverhältnis: max. bis zur ortsüblichen Vergleichsmiete
    -   Neubau/Erstbezug: keine gesetzlichen Einschränkungen

## Einführung

- Legaler Stand (Vertragsarten)
  - Indexmietverträge: an die Inflationsrate gekoppelt
  - Staffelmietverträge: Mieterhöhung in festgelegten Stufen
  - keine vertragliche Regelung: es gelten die allgemeinen gesetzlichen Bedingungen

## Überblick

-   Datenerhebung: Querschnittstudie
-   Art der Erhebung: Einwohnermeldedaten
    -   Zuvor: Telefonumfrage
    -   Ziehungsrahmen geänderet

## Betrachtete Merkmale

::: {.column width="300%" align="left" .custom-smaller}
<div class="custom-smaller">
```{r}
load("data/anfaengerprak_ws24.RData")
knitr::kable(head(anf.park.ws24, 4)) 
```
</div> 
:::

## Welchen Vermietertyp haben Preistreiberwohnungen
<<<<<<< Updated upstream

## Vermietertyp

::: {panel-tabset}
##Vergleichsgrafik 

grafik

##Vermietertypen grafik
:::

## Wohnfläche

::: {.panel-tabset}

### alle Mieten

Content for `Tab A`

### nur Preistreiber

Content for `Tab B`

:::

## Art des Mietvertrages

::: {.panel-tabset}

### alle Mieten

Content for `Tab A`

### nur Preistreiber

Content for `Tab B`

:::

## Zentral/Dezentral

## Lage
=======
>>>>>>> Stashed changes

<<<<<<< Updated upstream
## Limitationen

-   sehr kleinen Auszug aus dem Datensatz
-   615.000 Wohnungen, 3100 Stichprobengrösse
-   gerne mehr den legalen stand betrachtet
    -   aber: fehlende Informationen

<<<<<<< Updated upstream
## Fazit

-   Preistreiber haben keine expliziten Eigenschaften
-   kleine Unterschiede, aber keine Auffälligkeiten
=======
=======
>>>>>>> Stashed changes
## Makrolage

## Größe der Wohnungen

##

## Limitationen & Fazit
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
