---
title: "Armed conflicts - Armed conflicts between different groups in Nigeria over time"
institute: 
  - "Dr. Fabian Scheipl, Dr. Sabine Hoffmann, Helen Alber"
author: 
  - "Bob Faber, Adrian Schneider, Louis Trierweiler, Karan Bal"

format:
  revealjs:
    css: presentation/customstyle.css
    embed-resources: true
    slide-number: c
    theme: simple
editor: visual
---

## Gliederung

-   Fragestellung
-   Datenüberblick & Datenerhebung
-   Betrachtete Merkmale
-   Kontext
-   Deskriptive Analyse und Datenübersicht
-   Limitationen
-   Fazit
-   Diskussionen & Q&A

## Fragestellung

-   Zentrale Fragen:
    -   Entwicklung der Konflikttypen in Nigeria über die Zeit
    -   Zusammenhang zwischen Konfliktgruppen und Konflikttypen

## Datenüberblick & Datenerhebung

-   ACLED - Armed Conflict Location & Event Data
    
```     
-   non-profit Organisation
-   sammeln Daten zu politischen Konflikten und Protestereignissen
-   Ziel: Daten bereitstellen um Konflikte zu vermeiden
``` 
-   19 Merkmale mit 130.000 Observationen

## Datenüberblick & Datenerhebung

-   Art der Erhebung:

```         
    -   Längsschnitt
    -   Daten werden nicht von ACLED erhoben
    -   sekundäre Datenerhebungsart
    -   manuelle Codierung durch Gruppe von Analysten
```

-   Quellenbasis der Erhebung:

```         

    -   öffentlich verfügbare Informationen
    -   Zeitungsberichte
    -   Regierungsdokumente
    -   NGO- und UN-Berichte
    -   soziale Medien
    -   lokale Partner
```

## Betrachtete Merkmale

-   Konfliktnummer
-   Konfliktart
-   Konfliktbeteiligte
-   Standort
-   Nachrichtenquelle
-   Art der Nachrichtenquelle
-   Einwohneranzahl
-   Angriffe auf Zivilisten

## Kontext

-   Ethnische und religiöse Spannungen

    -   Boko Haram (seit 2010)

-   Interessenkonflikte um Öl im Niger-Delta

-   Korruption in der Regierung und Streitkräften

-   Klimawandel / Wüstenbildung im Norden

-   Radikalisierung während der Covid-Pandemie

## Netzwerkgraph



## Verlauf der klassischen Berichtsarten



## Verlauf der "New Media" Berichte



## Angriffe auf Zivilisten



## Konflikte verteilt in Nigeria



## Todesfälle pro Jahr


## Zusammenhang Bevölkerungsanzahl und Anzahl der Todesopfer



## Zusammenhang Akteurgruppen und Bevölkerungsanzahl



## Zusammenhang Konfliktgruppen und Konflikttypen



## Konflikttypen über die Zeit



## Limitationen

-   zu Anfang sehr wenige Observationen um das Jahr 2000
-   

## Fazit

-   Gibt es eine Veränderung der Konflikttypen über die Zeit?
-   Gibt es einen Zusammenhang zwischen Konflikttypen und Konlfiktgruppen?
-   Gab es einen Anstieg von Gewalt und Konflikten in Nigeria?

## Diskussion & Q&A

-   Gibt es mehr gemeldete Konflikte durch den vereinfachten Medienzugang?
-   Was kann man gegen die steigende Gewalt tuen, wer muss was ändern?
